/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import EDD.ListaDocs;
import EDD.MonticuloBinario;
import EDD.NodoLista;
import EDD.RegistroImpresion;
import Modelos.Documento;
import Modelos.Usuario;
import SO.Impresora;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 * Inicializa los componentes gráficos de la ventana principal y configura
 * la disposición visual de los paneles, botones, campos de texto, combos
 * y etiquetas que permiten interactuar con el sistema de impresión
 * @author valen
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    private Impresora impresora;
    
    private CardLayout cardLayoutCola;
    private JTextArea txtAreaSecuencia;
    private JTree treeCola;
    
    public Interfaz() {
        initComponents();
        impresora = new Impresora();

        TipoDocCrear.removeAllItems();
        TipoDocCrear.addItem("pdf");
        TipoDocCrear.addItem("docx");
        TipoDocCrear.addItem("txt");
        
        TipoUsuarioManual.removeAllItems();
        TipoUsuarioManual.addItem("Prioridad Alta");
        TipoUsuarioManual.addItem("Prioridad Media");
        TipoUsuarioManual.addItem("Prioridad Baja");

        actualizarCombosUsuariosDocumentos();
        inicializarVistaCola();
        refrescarVistaCola();
        actualizarComboUsuariosEnCola();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        CargarUsuarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        NombreUsuarioManual = new javax.swing.JTextField();
        AgregarUsuario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TipoUsuarioManual = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UsuarioAEliminar = new javax.swing.JComboBox<>();
        EliminarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MostrarUsuarios = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        UsuarioCrearDoc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NombreDocCrear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TamanoDocCrear = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TipoDocCrear = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        EliminarDocNoEnviado = new javax.swing.JButton();
        UsuarioGestionDoc = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DocumentoGestion = new javax.swing.JComboBox<>();
        EnviarImprimir = new javax.swing.JButton();
        CrearDocumento = new javax.swing.JButton();
        chkPrioritario = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        VistaCola = new javax.swing.JToggleButton();
        Imprimir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UsuarioCola = new javax.swing.JComboBox<>();
        DocumentoCola = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        EliminarEnCola = new javax.swing.JButton();
        PanelVistaCola = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        CargarUsuarios.setText("Cargar Usuarios");
        CargarUsuarios.addActionListener(this::CargarUsuariosActionPerformed);

        jLabel3.setText("Agrega un usuario manualmente");

        NombreUsuarioManual.addActionListener(this::NombreUsuarioManualActionPerformed);

        AgregarUsuario.setText("Agregar Usuario");
        AgregarUsuario.addActionListener(this::AgregarUsuarioActionPerformed);

        jLabel4.setText("Carga un archivo CSV. ");

        jLabel20.setText("Nombre:");

        jLabel21.setText("Tipo");

        TipoUsuarioManual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreUsuarioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoUsuarioManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AgregarUsuario)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CargarUsuarios))
                    .addComponent(jLabel3))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreUsuarioManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(TipoUsuarioManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarUsuarios)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Eliminar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ver Usuarios registrados");

        jLabel7.setText("Escoge usuarios a eliminar junto a sus documentos creados ");

        jLabel8.setText("que no se hayan enviado a imprimir");

        UsuarioAEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EliminarUsuario.setText("Eliminar Usuario");
        EliminarUsuario.addActionListener(this::EliminarUsuarioActionPerformed);

        MostrarUsuarios.setColumns(20);
        MostrarUsuarios.setRows(5);
        jScrollPane1.setViewportView(MostrarUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EliminarUsuario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsuarioAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UsuarioAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EliminarUsuario))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Usuarios", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        UsuarioCrearDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Seleccione tipo de documento");

        jLabel10.setText("Nombre del documento");

        jLabel11.setText("Indique numero de paginas");

        jLabel12.setText("Seleccione el nombre de usuario");

        TipoDocCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(65, 65, 65)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreDocCrear)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsuarioCrearDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TamanoDocCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoDocCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(63, 63, 63))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(UsuarioCrearDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NombreDocCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TamanoDocCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TipoDocCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Gestion de Documentos");

        EliminarDocNoEnviado.setText("Eliminar Documento");
        EliminarDocNoEnviado.setToolTipText("Eliminar documento seleccionado que no ha sido enviado a imprimir");
        EliminarDocNoEnviado.addActionListener(this::EliminarDocNoEnviadoActionPerformed);

        UsuarioGestionDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UsuarioGestionDoc.addActionListener(this::UsuarioGestionDocActionPerformed);

        jLabel15.setText("Seleccione nombre de usuario");

        jLabel16.setText("Seleccione el documento");

        DocumentoGestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EnviarImprimir.setText("Enviar a Imprimir");
        EnviarImprimir.addActionListener(this::EnviarImprimirActionPerformed);

        CrearDocumento.setText("Crear");
        CrearDocumento.addActionListener(this::CrearDocumentoActionPerformed);

        chkPrioritario.setText("Prioritario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CrearDocumento))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsuarioGestionDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(DocumentoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EliminarDocNoEnviado)
                            .addComponent(EnviarImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkPrioritario))))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearDocumento))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(EliminarDocNoEnviado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocumentoGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioGestionDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnviarImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPrioritario)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Documentos", jPanel2);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Cola de impresion");

        VistaCola.setText("Secuencia");
        VistaCola.addActionListener(this::VistaColaActionPerformed);

        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(this::ImprimirActionPerformed);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Documento en Cola", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel17.setText("Seleccione nombre de usuario");

        jLabel18.setText("Seleccione el documento");

        UsuarioCola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UsuarioCola.addActionListener(this::UsuarioColaActionPerformed);

        DocumentoCola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(UsuarioCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(DocumentoCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DocumentoCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setText("Vista:");

        EliminarEnCola.setText("Eliminar");
        EliminarEnCola.addActionListener(this::EliminarEnColaActionPerformed);

        javax.swing.GroupLayout PanelVistaColaLayout = new javax.swing.GroupLayout(PanelVistaCola);
        PanelVistaCola.setLayout(PanelVistaColaLayout);
        PanelVistaColaLayout.setHorizontalGroup(
            PanelVistaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        PanelVistaColaLayout.setVerticalGroup(
            PanelVistaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelVistaCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VistaCola)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Imprimir)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(EliminarEnCola)
                                .addGap(9, 9, 9)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VistaCola)
                    .addComponent(jLabel19)
                    .addComponent(Imprimir))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelVistaCola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarEnCola)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cola de Impresion", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Maneja la acción de registrar un nuevo usuario en el sistema a partir
     * de los datos introducidos en la interfaz. Si el registro es exitoso,
     * actualiza los combos y listas relacionadas.
     *
     * @param evt evento generado por la acción del usuario
     */
    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        String nombre = NombreUsuarioManual.getText().trim();
        String tipoSeleccionado = TipoUsuarioManual.getSelectedItem().toString();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debes ingresar el nombre del usuario.",
                    "Campo vacío",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String tipo;
        switch (tipoSeleccionado) {
            case "Prioridad Alta":
                tipo = "prioridad_alta";
                break;
            case "Prioridad Media":
                tipo = "prioridad_media";
                break;
            default:
                tipo = "regular";
                break;
        }
        boolean agregado = impresora.agregarUsuario(nombre, tipo);

        if (agregado) {
            JOptionPane.showMessageDialog(this, "Usuario agregado correctamente.");
            NombreUsuarioManual.setText("");
            mostrarUsuariosRegistrados();
            actualizarComboEliminarUsuarios();
            actualizarCombosUsuariosDocumentos();
            actualizarComboUsuariosEnCola();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ese usuario ya existe.",
                    "Usuario duplicado",
                    JOptionPane.ERROR_MESSAGE);
        }    
        
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void NombreUsuarioManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioManualActionPerformed

    }//GEN-LAST:event_NombreUsuarioManualActionPerformed
    
    /**
    * Maneja la acción de cargar usuarios desde un archivo CSV seleccionado
    * mediante un selector de archivos. Si la carga es exitosa, actualiza
    * los componentes visuales relacionados con usuarios y cola.
    *
    * @param evt evento generado por la acción del usuario
    */
    private void CargarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarUsuariosActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Selecciona el archivo CSV de usuarios");
        int resultado = chooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();

            try {
                impresora.inicializarUsuariosDesdeCSV(archivo);
                JOptionPane.showMessageDialog(this, "Usuarios cargados correctamente.");
                mostrarUsuariosRegistrados();
                actualizarComboEliminarUsuarios();
                actualizarCombosUsuariosDocumentos();
                actualizarComboUsuariosEnCola();
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error al cargar el archivo: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_CargarUsuariosActionPerformed
   
    /**
     * Maneja la acción de eliminar un usuario seleccionado de la lista de
     * usuarios registrados. Si no hay usuario seleccionado, muestra una
     * advertencia y no ejecuta cambios.
     *
     * @param evt evento generado por la acción del usuario
     */
    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        if (UsuarioAEliminar.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay usuarios para eliminar.",
                    "Sin usuarios",
                    JOptionPane.WARNING_MESSAGE);
            return;
}
        String nombreUsuario =UsuarioAEliminar.getSelectedItem().toString();
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar al usuario " + nombreUsuario + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        boolean eliminado = impresora.eliminarUsuario(nombreUsuario);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
            mostrarUsuariosRegistrados();
            actualizarComboEliminarUsuarios();
            actualizarCombosUsuariosDocumentos();
            actualizarComboUsuariosEnCola();
            refrescarVistaCola();
            
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el usuario.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void UsuarioGestionDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioGestionDocActionPerformed
        actualizarComboDocumentosGestion();
    }//GEN-LAST:event_UsuarioGestionDocActionPerformed
    
    /**
 * Maneja la acción de crear un nuevo documento asociado al usuario
 * seleccionado en la interfaz, utilizando los datos de nombre y
 * número de páginas introducidos por el usuario.
 *
 * @param evt evento generado por la acción del usuario
 */
    private void CrearDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDocumentoActionPerformed
        String nombreUsuario = UsuarioCrearDoc.getSelectedItem() != null
                ? UsuarioCrearDoc.getSelectedItem().toString()
                : "";

        String nombreDocumento = NombreDocCrear.getText().trim();
        String paginasTexto = TamanoDocCrear.getText().trim();
        String tipoDocumento = TipoDocCrear.getSelectedItem() != null
                ? TipoDocCrear.getSelectedItem().toString()
                : "";

        if (nombreUsuario.isEmpty() || nombreDocumento.isEmpty() || paginasTexto.isEmpty() || tipoDocumento.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debes completar todos los campos para crear el documento.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int paginas;
        try {
            paginas = Integer.parseInt(paginasTexto);
            if (paginas <= 0) {
                JOptionPane.showMessageDialog(this,
                        "El número de páginas debe ser mayor que cero.",
                        "Dato inválido",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "El número de páginas debe ser un valor numérico.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean creado = impresora.crearDocumento(nombreUsuario, nombreDocumento, paginas, tipoDocumento);

        if (creado) {
            JOptionPane.showMessageDialog(this,
                    "Documento creado correctamente.");
            NombreDocCrear.setText("");
            TamanoDocCrear.setText("");
            actualizarComboDocumentosGestion();
            mostrarUsuariosRegistrados();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo crear el documento. Puede que el usuario no exista o que ya tenga un documento con ese nombre.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearDocumentoActionPerformed
   
    /**
     * Elimina un documento que aún no ha sido enviado a la cola de impresión,
     * siempre que pertenezca al usuario seleccionado y continúe disponible
     * para gestión directa.
     *
     * @param evt evento generado por la acción del usuario
     */
    private void EliminarDocNoEnviadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocNoEnviadoActionPerformed
        if (UsuarioGestionDoc.getSelectedItem() == null || DocumentoGestion.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debes seleccionar un usuario y un documento.",
                    "Selección incompleta",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombreUsuario = UsuarioGestionDoc.getSelectedItem().toString();
        String nombreDocumento = DocumentoGestion.getSelectedItem().toString();

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar el documento " + nombreDocumento + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        boolean eliminado = impresora.eliminarDocumentoNoEnviado(nombreUsuario, nombreDocumento);

        if (eliminado) {
            JOptionPane.showMessageDialog(this,
                    "Documento eliminado correctamente.");
            actualizarComboDocumentosGestion();
            mostrarUsuariosRegistrados();
            refrescarVistaCola();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el documento. Puede que ya esté en cola o que no exista.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
}        
    }//GEN-LAST:event_EliminarDocNoEnviadoActionPerformed
    
    /**
 * Maneja la acción de enviar un documento a la cola de impresión.
 * Toma el usuario y el documento seleccionados, junto con la opción
 * de prioridad, y solicita al backend su inserción en la cola.Si el usuario
 * es de prioridad alta y no esta marcado como prioritario, el sistema pregunta 
 * si desea marcarlo.
 *
 * @param evt evento generado por la acción del usuario
 */
    private void EnviarImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarImprimirActionPerformed
        if (UsuarioGestionDoc.getSelectedItem() == null || DocumentoGestion.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debes seleccionar un usuario y un documento.",
                    "Selección incompleta",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombreUsuario = UsuarioGestionDoc.getSelectedItem().toString();
        String nombreDocumento = DocumentoGestion.getSelectedItem().toString();
        boolean prioritario = chkPrioritario.isSelected();
        Usuario usuario = impresora.buscarUsuario(nombreUsuario);

        if (usuario != null && !prioritario) {
            String tipo = usuario.getTipo().toLowerCase();

            if (tipo.equals("prioridad_alta") || tipo.equals("prioridad_media")) {
                int opcion = JOptionPane.showConfirmDialog(
                        this,
                        "Este usuario es de " + tipo.replace("_", " ") +
                        ". ¿Desea marcar el documento como prioritario?",
                        "Confirmar prioridad",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (opcion == JOptionPane.CANCEL_OPTION) {
                    return;
                }

                if (opcion == JOptionPane.YES_OPTION) {
                    chkPrioritario.setSelected(true);
                    prioritario = true;
                }
            }
        }
        boolean enviado = impresora.enviarImprimir(nombreUsuario, nombreDocumento, prioritario);
        if (enviado) {
            JOptionPane.showMessageDialog(this,
                    "Documento enviado a imprimir correctamente.");
            actualizarComboDocumentosGestion();
            mostrarUsuariosRegistrados();
            chkPrioritario.setSelected(false);
            refrescarVistaCola();
            actualizarComboUsuariosEnCola();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo enviar el documento a imprimir.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }     
    }//GEN-LAST:event_EnviarImprimirActionPerformed
   
    /**
     * Vista de la cola de impresion, puede ser en forma de arbol o secuencia, se decide
     * con toggle btn.
     * @param evt 
     */
    private void VistaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaColaActionPerformed
        if (VistaCola.isSelected()) {
            cardLayoutCola.show(PanelVistaCola, "ARBOL");
            VistaCola.setText("Cambiar a Secuencia");
        } else {
            cardLayoutCola.show(PanelVistaCola, "SECUENCIA");
            VistaCola.setText("Cambiar a Árbol");
        }
        refrescarVistaCola();
    }//GEN-LAST:event_VistaColaActionPerformed

    /**
    * Maneja el cambio de selección del usuario en cola para actualizar
    * la lista de documentos en cola correspondientes a dicho usuario.
    *
    * @param evt evento generado por la acción del usuario
    */
    private void UsuarioColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioColaActionPerformed
        actualizarComboDocumentosEnCola();
    }//GEN-LAST:event_UsuarioColaActionPerformed

    /**
 * Maneja la acción de procesar la impresión del siguiente documento en cola.
 * Si existe un documento pendiente, solicita su impresión y actualiza la
 * información mostrada en la interfaz.
 *
 * @param evt evento generado por la acción del usuario
 */
    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        Documento impreso = impresora.liberarImpresora();

        if (impreso == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay documentos en la cola de impresión.",
                    "Cola vacía",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this,
                "Se imprimió el documento: " + impreso.getId());

        mostrarUsuariosRegistrados();
        actualizarComboDocumentosGestion();
        actualizarComboUsuariosEnCola();
        refrescarVistaCola();
    }//GEN-LAST:event_ImprimirActionPerformed

    /**
 * Maneja la acción de cancelar o eliminar un documento que se encuentra
 * actualmente en la cola de impresión, usando el usuario y documento
 * seleccionados en los combos correspondientes.
 *
 * @param evt evento generado por la acción del usuario
 */
    private void EliminarEnColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEnColaActionPerformed
        if (UsuarioCola.getSelectedItem() == null || DocumentoCola.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debes seleccionar un usuario y un documento en cola.",
                    "Selección incompleta",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombreUsuario = UsuarioCola.getSelectedItem().toString();
        String nombreDocumento = DocumentoCola.getSelectedItem().toString();

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar de la cola el documento " + nombreDocumento + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        boolean eliminado = impresora.cancelarImpresion(nombreUsuario, nombreDocumento);

        if (eliminado) {
            JOptionPane.showMessageDialog(this,
                    "Documento eliminado de la cola correctamente.");
            mostrarUsuariosRegistrados();
            actualizarComboDocumentosGestion();
            actualizarComboUsuariosEnCola();
            refrescarVistaCola();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el documento de la cola.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarEnColaActionPerformed

    /**
 * Actualiza el combo de usuarios disponibles para ser eliminados del sistema,
 * según la lista actual de usuarios registrados.
 */
    private void actualizarComboEliminarUsuarios() {
        UsuarioAEliminar.removeAllItems();

        ListaDocs<Usuario> lista = impresora.getUsuariosRegistrados();

        if (lista == null || lista.esVacia()) {
            UsuarioAEliminar.setEnabled(false);
            DocumentoCola.setEnabled(false);
            return;
        }

        NodoLista<Usuario> actual = lista.getFirst();
        while (actual != null) {
            UsuarioAEliminar.addItem(actual.getInfo().getNombre());
            actual = actual.getNext();
        }

        UsuarioAEliminar.setEnabled(true);
        DocumentoCola.setEnabled(true);

    }  
    
    /**
    * Muestra en la interfaz la lista de usuarios actualmente registrados
    * en el sistema.
    */
    private void mostrarUsuariosRegistrados() {
    ListaDocs<Usuario> listaUsuarios = impresora.getUsuariosRegistrados();

    if (listaUsuarios == null || listaUsuarios.esVacia()) {
        MostrarUsuarios.setText("No hay usuarios registrados.");
        return;
    }
    StringBuilder sb = new StringBuilder();
    NodoLista<Usuario> actualUsuario = listaUsuarios.getFirst();
    int i = 1;
    while (actualUsuario != null) {
        Usuario usuario = actualUsuario.getInfo();

        sb.append("Usuario ").append(i).append("\n");
        sb.append("Nombre: ").append(usuario.getNombre()).append("\n");
        sb.append("Tipo: ").append(usuario.getTipo()).append("\n");
        sb.append("Documentos:\n");

        ListaDocs<Documento> listaDocs = usuario.getDocumentosCreados();

        if (listaDocs == null || listaDocs.esVacia()) {
            sb.append("  - No tiene documentos creados.\n");
        } else {
            NodoLista<Documento> actualDoc = listaDocs.getFirst();

            while (actualDoc != null) {
                Documento doc = actualDoc.getInfo();

                sb.append("  - ID: ").append(doc.getId())
                  .append(" | Tipo: ").append(doc.getTipo())
                  .append(" | Estado: ")
                  .append(doc.isEnCola() ? "EN COLA" : "NO ENVIADO")
                  .append("\n");

                actualDoc = actualDoc.getNext();
            }
        }
        sb.append("\n----------------------------------------\n");
        actualUsuario = actualUsuario.getNext();
        i++;
    }
    MostrarUsuarios.setText(sb.toString());
}
    
    /**
    * Actualiza los combos relacionados con la gestión de documentos de los
    * usuarios, según el usuario actualmente seleccionado y el estado del sistema.
    */
    private void actualizarCombosUsuariosDocumentos() {
        UsuarioCrearDoc.removeAllItems();
        UsuarioGestionDoc.removeAllItems();

        ListaDocs<Usuario> lista = impresora.getUsuariosRegistrados();

        if (lista == null || lista.esVacia()) {
            UsuarioCrearDoc.setEnabled(false);
            UsuarioGestionDoc.setEnabled(false);
            DocumentoGestion.removeAllItems();
            CrearDocumento.setEnabled(false);
            EliminarDocNoEnviado.setEnabled(false);
            EnviarImprimir.setEnabled(false);
            return;
        }

        NodoLista<Usuario> actual = lista.getFirst();
        while (actual != null) {
            String nombre = actual.getInfo().getNombre();
            UsuarioCrearDoc.addItem(nombre);
            UsuarioGestionDoc.addItem(nombre);
            actual = actual.getNext();
        }

        UsuarioCrearDoc.setEnabled(true);
        UsuarioGestionDoc.setEnabled(true);
        CrearDocumento.setEnabled(true);
        actualizarComboDocumentosGestion();
    }
    
    /**
    * Actualiza el combo de documentos disponibles para operaciones de gestión,
    * tomando en cuenta el usuario seleccionado y los documentos asociados a este.
    */
    private void actualizarComboDocumentosGestion() {
        DocumentoGestion.removeAllItems();

        if (UsuarioGestionDoc.getSelectedItem() == null) {
            DocumentoGestion.setEnabled(false);
            EliminarDocNoEnviado.setEnabled(false);
            EnviarImprimir.setEnabled(false);
            return;
        }

        String nombreUsuario = UsuarioGestionDoc.getSelectedItem().toString();
        Usuario usuario = impresora.buscarUsuario(nombreUsuario);

        if (usuario == null || usuario.getDocumentosCreados() == null || usuario.getDocumentosCreados().esVacia()) {
            DocumentoGestion.setEnabled(false);
            EliminarDocNoEnviado.setEnabled(false);
            EnviarImprimir.setEnabled(false);
            return;
        }

        ListaDocs<Documento> listaDocs = usuario.getDocumentosCreados();
        NodoLista<Documento> actual = listaDocs.getFirst();

        while (actual != null) {
            Documento doc = actual.getInfo();

            // Solo muestra documentos no enviados todavía.
            if (!doc.isEnCola()) {
                DocumentoGestion.addItem(doc.getId());
            }

            actual = actual.getNext();
        }
        boolean hayDocs = DocumentoGestion.getItemCount() > 0;
        DocumentoGestion.setEnabled(hayDocs);
        EliminarDocNoEnviado.setEnabled(hayDocs);
        EnviarImprimir.setEnabled(hayDocs);
    }
    
    /**
     * Inicializa la vista gráfica de la cola de impresión, preparando sus
     * componentes visuales y cargando la información inicial correspondiente.
     */
    private void inicializarVistaCola() {
        cardLayoutCola = new CardLayout();
        PanelVistaCola.setLayout(cardLayoutCola);

        txtAreaSecuencia = new JTextArea();
        txtAreaSecuencia.setEditable(false);
        JScrollPane scrollSecuencia = new JScrollPane(txtAreaSecuencia);

        treeCola = new JTree(new DefaultMutableTreeNode("Cola vacía"));
        JScrollPane scrollArbol = new JScrollPane(treeCola);

        PanelVistaCola.add(scrollSecuencia, "SECUENCIA");
        PanelVistaCola.add(scrollArbol, "ARBOL");

        cardLayoutCola.show(PanelVistaCola, "SECUENCIA");

        VistaCola.setSelected(false);
        VistaCola.setText("Cambiar a Árbol");
    }

    /**
    * Refresca la vista de la cola de impresión para reflejar el estado actual
    * de los documentos pendientes dentro del sistema.
    */
    private void refrescarVistaCola() {
        txtAreaSecuencia.setText(construirTextoSecuencia());
        treeCola.setModel(new DefaultTreeModel(construirArbolHeap()));
     }
    
    /**
    * Construye el texto que representa la secuencia actual de impresión,
    * mostrando de forma ordenada los documentos presentes en la cola.
    *
    * @return representación textual de la secuencia de impresión
    */
    private String construirTextoSecuencia() {
        MonticuloBinario cola = impresora.getColaImpresion();

        if (cola == null || cola.esVacio()) {
            return "La cola de impresión está vacía.";
        }
        StringBuilder sb = new StringBuilder();
        RegistroImpresion[] arreglo = cola.getArregloInterno();
        int tam = cola.getTamano();

        for (int i = 0; i < tam; i++) {
            RegistroImpresion reg = arreglo[i];
            if (reg != null) {
                Documento doc = reg.getDocumento();

                sb.append("Posición ").append(i)
                  .append(" | Documento: ").append(doc.getId())
                  .append(" | Tipo: ").append(doc.getTipo())
                  .append(" | Tag: ").append(reg.getTimetag())
                  .append("\n");
            }
        }
        return sb.toString();
    }
    
    /**
    * Construye la representación en forma de árbol del montículo binario
    * utilizado para modelar la cola de impresión, con fines de visualización
    * dentro de la interfaz.
    *
    * @return nodo raíz del árbol visual que representa el heap
    */
    private DefaultMutableTreeNode construirArbolHeap() {
        MonticuloBinario cola = impresora.getColaImpresion();

        if (cola == null || cola.esVacio()) {
            return new DefaultMutableTreeNode("Cola vacía");
        }

        RegistroImpresion[] arreglo = cola.getArregloInterno();
        int tam = cola.getTamano();

        DefaultMutableTreeNode[] nodos = new DefaultMutableTreeNode[tam];

        for (int i = 0; i < tam; i++) {
            RegistroImpresion reg = arreglo[i];
            Documento doc = reg.getDocumento();

            String textoNodo = doc.getId() + " (tag=" + reg.getTimetag() + ")";
            nodos[i] = new DefaultMutableTreeNode(textoNodo);
        }

        for (int i = 0; i < tam; i++) {
            int izq = 2 * i + 1;
            int der = 2 * i + 2;

            if (izq < tam) {
                nodos[i].add(nodos[izq]);
            }
            if (der < tam) {
                nodos[i].add(nodos[der]);
            }
        }
        return nodos[0];
}
    
    /**
    * Actualiza el combo de usuarios que actualmente tienen documentos en cola,
    * a partir del contenido real de la cola de impresión.
    */
    private void actualizarComboUsuariosEnCola() {
        UsuarioCola.removeAllItems();

        ListaDocs<String> usuariosEnCola = impresora.getUsuariosConDocumentosEnCola();

        if (usuariosEnCola == null || usuariosEnCola.esVacia()) {
            UsuarioCola.setEnabled(false);
            DocumentoCola.removeAllItems();
            DocumentoCola.setEnabled(false);
            EliminarEnCola.setEnabled(false);
            return;
        }

        NodoLista<String> actualUsuario = usuariosEnCola.getFirst();
        while (actualUsuario != null) {
            UsuarioCola.addItem(actualUsuario.getInfo());
            actualUsuario = actualUsuario.getNext();
        }

        UsuarioCola.setEnabled(true);
        actualizarComboDocumentosEnCola();
    }
    
    /**
    * Actualiza el combo de documentos en cola correspondientes al usuario
    * seleccionado en el combo de usuarios con documentos pendientes.
    */
    private void actualizarComboDocumentosEnCola() {
        DocumentoCola.removeAllItems();

        if (UsuarioCola.getSelectedItem() == null) {
            DocumentoCola.setEnabled(false);
            EliminarEnCola.setEnabled(false);
            return;
        }
        String nombreUsuario = UsuarioCola.getSelectedItem().toString();
        ListaDocs<String> documentosEnCola = impresora.getDocumentosEnColaDeUsuario(nombreUsuario);

           if (documentosEnCola == null || documentosEnCola.esVacia()) {
               DocumentoCola.setEnabled(false);
               EliminarEnCola.setEnabled(false);
               return;
           }

           NodoLista<String> actualDoc = documentosEnCola.getFirst();
           while (actualDoc != null) {
               DocumentoCola.addItem(actualDoc.getInfo());
               actualDoc = actualDoc.getNext();
           }

           DocumentoCola.setEnabled(true);
           EliminarEnCola.setEnabled(true);
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JButton CargarUsuarios;
    private javax.swing.JButton CrearDocumento;
    private javax.swing.JComboBox<String> DocumentoCola;
    private javax.swing.JComboBox<String> DocumentoGestion;
    private javax.swing.JButton EliminarDocNoEnviado;
    private javax.swing.JButton EliminarEnCola;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JButton EnviarImprimir;
    private javax.swing.JButton Imprimir;
    private javax.swing.JTextArea MostrarUsuarios;
    private javax.swing.JTextField NombreDocCrear;
    private javax.swing.JTextField NombreUsuarioManual;
    private javax.swing.JPanel PanelVistaCola;
    private javax.swing.JTextField TamanoDocCrear;
    private javax.swing.JComboBox<String> TipoDocCrear;
    private javax.swing.JComboBox<String> TipoUsuarioManual;
    private javax.swing.JComboBox<String> UsuarioAEliminar;
    private javax.swing.JComboBox<String> UsuarioCola;
    private javax.swing.JComboBox<String> UsuarioCrearDoc;
    private javax.swing.JComboBox<String> UsuarioGestionDoc;
    private javax.swing.JToggleButton VistaCola;
    private javax.swing.JCheckBox chkPrioritario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
